lb:
  image: rancher/load-balancer-service
  ports:
  # Assign a random public port and direct traffic to private port 80 of the service.
  - 80
  # Listen on public port 80 and direct traffic to private port 80 of the service
  - 80:80
  # Listen on public port 82 and by default forward traffic to private port 81 using HTTP
  - 82:81
  # Listen on public port 9999 using TCP and not HTTP
  - 9999/tcp
  links:
  # Target services in the same stack will be listed as a link
  - web:web
web:
  build: .
  env_file: ./env
  labels:
    - "io.rancher.container.network=true"
    - "io.rancher.scheduler.global=true"	
    - "io.rancher.container.hostname_override=container_name"
#redis:
  #image: redis
