lb:
  image: rancher/load-balancer-service
  ports:
  # Listen on public port 80 and direct traffic to private port 80 of the service
  - 80:80
  links:
  # Target services in the same stack will be listed as a link
  - web:web
web:
  build: .
  env_file: ./env
  labels:
    - "io.rancher.container.network=true"
    - "io.rancher.scheduler.global=true"	
    - "io.rancher.container.hostname_override=container_name"
#redis:
  #image: redis
